import { authStateChanged, loginWithGitHub } from "../firebase/client"
import Head from "next/head"

import { useEffect, useState } from "react"

import { colors } from "styles/theme"

import AppLayout from "components/AppLayout"
import Avatar from "components/Avatar"
import Button from "components/Button"
import GitHub from "components/Icons/Github"
import Logo from "components/Icons/Logo"

export default function Home () {
  const [user, setUser] = useState( undefined )

  useEffect( () => {
    authStateChanged( setUser )
  }, [] )

  const handleClick = () => {
    loginWithGitHub()
      .then( ( user ) => {
        setUser( user )
      } )
      .catch( ( err ) => console.log( err ) )
  }

  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <Logo
            height='140px'
          />
          <h1>Devter</h1>
          <h2>Talk about development with developers 👨‍💻👩‍💻</h2>
          <div>
            { user === null && (
              <Button onClick={ handleClick }>
                <GitHub height="2rem" width="2rem" fill="#fff" />
                Login with GitHub
              </Button>
            ) }
            { user && user.avatar && (
              <div>
                <Avatar
                  src={ user.avatar }
                  alt={ user.username }
                  text={ user.username }
                />
              </div>
            ) }
          </div>
        </section>
      </AppLayout>

      <style jsx>
        { `
          h1 {
            color: ${colors.primary};
            font-weight: 800;
            font-size: 2rem;
            margin-bottom: 1rem;
          }
          h2 {
            font-size: 1.5rem;
            width: 80%;
            color: ${colors.secondary};
            margin: 0;
          }
          section {
            display: grid;
            place-items: center;
            place-content: center;
            height: 100%;
          }
          div {
            padding: 1rem;
          }
        `}
      </style>
    </>
  )
}
