import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<>
			<Head>
				<title>Devter</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					<Link href='https://nextjs.org'>Devter</Link>
				</h1>
				<nav className={styles.nav}>
					<Link href='/timeline'>Timeline</Link>
				</nav>
			</main>
		</>
	)
}
